# Generated by Django 5.0.14 on 2026-08-25 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('current_soc_percent', models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_soc_percent', models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maximum_soc_percent', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('charging_efficiency', models.FloatField(default=90, help_text='Charging efficiency as a percentage.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('maximum_charge_rate_kw', models.FloatField(blank=True, null=True)),
                ('maximum_discharge_rate_kw', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GridConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_tariff_per_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('export_tariff_per_kwh', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('export_enabled', models.BooleanField(default=False)),
                ('net_metering_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gridconfiguration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('ON_GRID', 'On-Grid'), ('OFF_GRID', 'Off-Grid'), ('HYBRID', 'Hybrid')], max_length=10)),
                ('capacity_kw', models.FloatField(help_text='Installed solar panel capacity in kW.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1000)])),
                ('panel_count', models.PositiveIntegerField(blank=True, null=True)),
                ('inverter_capacity_kw', models.FloatField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solarsystem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
