# Generated by Django 5.0.14 on 2026-08-26 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='capacity_kwh',
            field=models.FloatField(help_text='Total usable storage capacity of your battery, in kWh (e.g. a 5 kWh battery).', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='battery',
            name='charging_efficiency',
            field=models.FloatField(default=90, help_text='Percentage of energy actually stored vs. energy put in — accounts for losses as heat while charging.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='battery',
            name='current_soc_percent',
            field=models.FloatField(default=50, help_text='Current State of Charge — how full the battery is right now (%). Update this manually whenever you check it.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='battery',
            name='maximum_charge_rate_kw',
            field=models.FloatField(blank=True, help_text='Optional: fastest rate (kW) your battery can be charged at. Leave blank if unknown.', null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='maximum_discharge_rate_kw',
            field=models.FloatField(blank=True, help_text='Optional: fastest rate (kW) your battery can be discharged at. Leave blank if unknown.', null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='maximum_soc_percent',
            field=models.FloatField(default=100, help_text='Highest charge level the battery should be charged to (often 100%, sometimes capped lower for longevity).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='battery',
            name='minimum_soc_percent',
            field=models.FloatField(default=20, help_text='Lowest charge level the battery should be allowed to drop to, to protect battery health (commonly 20%).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='gridconfiguration',
            name='export_enabled',
            field=models.BooleanField(default=False, help_text='Does your connection allow exporting surplus solar power back to the grid?'),
        ),
        migrations.AlterField(
            model_name='gridconfiguration',
            name='export_tariff_per_kwh',
            field=models.FloatField(blank=True, help_text="What you're paid/credited per kWh of surplus solar exported to the grid. Leave blank if not paid separately.", null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gridconfiguration',
            name='import_tariff_per_kwh',
            field=models.FloatField(help_text='What your electricity provider charges per kWh drawn from the grid (used to estimate savings).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gridconfiguration',
            name='net_metering_enabled',
            field=models.BooleanField(default=False, help_text='Does your utility offset your bill using exported units (net metering) instead of a separate cash payment?'),
        ),
    ]
