# Generated by Django 5.0.14 on 2026-08-28 12:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_alter_battery_capacity_kwh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Your own label for this appliance, e.g. 'Kitchen Fridge', 'Bedroom AC 1'.", max_length=100)),
                ('category', models.CharField(help_text="Functional group, e.g. 'Refrigeration', 'Cooling', 'Laundry'. Used to group appliances, not to identify a single one.", max_length=100)),
                ('rated_power_w', models.FloatField(help_text='Power rating in Watts, usually printed on the appliance nameplate.', validators=[django.core.validators.MinValueValidator(1)])),
                ('average_usage_hours', models.FloatField(help_text='Typical hours per day this appliance runs.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('daily_energy_kwh', models.FloatField(default=0, editable=False, help_text='Auto-calculated: rated power (W) x usage hours / 1000.')),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('is_shiftable', models.BooleanField(default=False, help_text="Can this appliance's usage time be moved to align with solar availability?")),
                ('solar_preferred', models.BooleanField(default=True, help_text='Should the system try to schedule this appliance during solar generation hours?')),
                ('preferred_start_time', models.TimeField(blank=True, help_text="Optional: earliest time you'd normally like this appliance running.", null=True)),
                ('preferred_end_time', models.TimeField(blank=True, help_text="Optional: latest time you'd normally like this appliance running.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SolarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('generation_kwh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CSV', 'CSV Upload'), ('INVERTER', 'Inverter (future)')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
