# Generated by Django 5.0.14 on 2026-09-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_appliance_solargeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsystem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
